### ISSUE TITLE
How to hide the scroll bar beside image?

### ISSUE THREAD

**Issue by Rahul108** [plangrid/react-file-viewer#185]
I'm using `FileViewer` like this:
```js
<div className={documentClasses.documentViewStyle}>
    <FileViewer
        filePath={`/media/${props.currentPath}`}
        fileType={getExtension(props.currentPath)}
    />
</div>
```
css:
```css
documentViewStyle: {
    margin: 'auto',
    width: '1000px',
    height: '700px',
    backgroundColor: '#FFFFFF',
}
```

A scrollbar appears beside every item (Image, pdf... etc). How can I hide this scrollbar? It seems like the scrollbar is appearing from the `FileViewer` component if I'm not wrong. Is there any way to override any css property on this component?
